/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterMitraRouteImport } from './routes/register-mitra'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthenticatedWorkOrderRouteImport } from './routes/_authenticated/work-order'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReportPengirimanRouteImport } from './routes/_authenticated/report-pengiriman'
import { Route as AuthenticatedReportPenerimaanRouteImport } from './routes/_authenticated/report-penerimaan'
import { Route as AuthenticatedProductionSummaryRouteImport } from './routes/_authenticated/production-summary'
import { Route as AuthenticatedPokemonRouteImport } from './routes/_authenticated/pokemon'
import { Route as AuthenticatedPoInternalRouteImport } from './routes/_authenticated/po-internal'
import { Route as AuthenticatedPoClientRouteImport } from './routes/_authenticated/po-client'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedMitraRouteImport } from './routes/_authenticated/mitra'
import { Route as AuthenticatedJenisBarangRouteImport } from './routes/_authenticated/jenis-barang'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedDepartemenRouteImport } from './routes/_authenticated/departemen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedBarangRouteImport } from './routes/_authenticated/barang'
import { Route as AuthenticatedAiEstimationRouteImport } from './routes/_authenticated/ai-estimation'
import { Route as AuthenticatedWorkOrderIndexRouteImport } from './routes/_authenticated/work-order.index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles.index'
import { Route as AuthenticatedReportPengirimanIndexRouteImport } from './routes/_authenticated/report-pengiriman.index'
import { Route as AuthenticatedReportPenerimaanIndexRouteImport } from './routes/_authenticated/report-penerimaan.index'
import { Route as AuthenticatedPoInternalIndexRouteImport } from './routes/_authenticated/po-internal.index'
import { Route as AuthenticatedPoClientIndexRouteImport } from './routes/_authenticated/po-client.index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions.index'
import { Route as AuthenticatedMitraIndexRouteImport } from './routes/_authenticated/mitra.index'
import { Route as AuthenticatedJenisBarangIndexRouteImport } from './routes/_authenticated/jenis-barang.index'
import { Route as AuthenticatedDepartemenIndexRouteImport } from './routes/_authenticated/departemen.index'
import { Route as AuthenticatedBarangIndexRouteImport } from './routes/_authenticated/barang.index'
import { Route as AuthenticatedWorkOrderCreateRouteImport } from './routes/_authenticated/work-order.create'
import { Route as AuthenticatedWorkOrderIdRouteImport } from './routes/_authenticated/work-order.$id'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated/users.create'
import { Route as AuthenticatedRolesCreateRouteImport } from './routes/_authenticated/roles.create'
import { Route as AuthenticatedReportPengirimanCreateRouteImport } from './routes/_authenticated/report-pengiriman.create'
import { Route as AuthenticatedReportPengirimanIdRouteImport } from './routes/_authenticated/report-pengiriman.$id'
import { Route as AuthenticatedReportPenerimaanCreateRouteImport } from './routes/_authenticated/report-penerimaan.create'
import { Route as AuthenticatedReportPenerimaanIdRouteImport } from './routes/_authenticated/report-penerimaan.$id'
import { Route as AuthenticatedPoInternalCreateRouteImport } from './routes/_authenticated/po-internal.create'
import { Route as AuthenticatedPoInternalIdRouteImport } from './routes/_authenticated/po-internal.$id'
import { Route as AuthenticatedPoClientCreateRouteImport } from './routes/_authenticated/po-client.create'
import { Route as AuthenticatedPoClientIdRouteImport } from './routes/_authenticated/po-client.$id'
import { Route as AuthenticatedPermissionsCreateRouteImport } from './routes/_authenticated/permissions.create'
import { Route as AuthenticatedPermissionsIdRouteImport } from './routes/_authenticated/permissions.$id'
import { Route as AuthenticatedMitraCreateRouteImport } from './routes/_authenticated/mitra.create'
import { Route as AuthenticatedMitraIdRouteImport } from './routes/_authenticated/mitra.$id'
import { Route as AuthenticatedJenisBarangCreateRouteImport } from './routes/_authenticated/jenis-barang.create'
import { Route as AuthenticatedJenisBarangIdRouteImport } from './routes/_authenticated/jenis-barang.$id'
import { Route as AuthenticatedDepartemenCreateRouteImport } from './routes/_authenticated/departemen.create'
import { Route as AuthenticatedDepartemenIdRouteImport } from './routes/_authenticated/departemen.$id'
import { Route as AuthenticatedBarangCreateRouteImport } from './routes/_authenticated/barang.create'
import { Route as AuthenticatedBarangIdRouteImport } from './routes/_authenticated/barang.$id'
import { Route as AuthenticatedWorkOrderEditIdRouteImport } from './routes/_authenticated/work-order.edit.$id'
import { Route as AuthenticatedUsersEditIdRouteImport } from './routes/_authenticated/users.edit.$id'
import { Route as AuthenticatedRolesEditIdRouteImport } from './routes/_authenticated/roles.edit.$id'
import { Route as AuthenticatedReportPengirimanEditIdRouteImport } from './routes/_authenticated/report-pengiriman.edit.$id'
import { Route as AuthenticatedReportPenerimaanEditIdRouteImport } from './routes/_authenticated/report-penerimaan.edit.$id'
import { Route as AuthenticatedPoClientEditIdRouteImport } from './routes/_authenticated/po-client.edit.$id'
import { Route as AuthenticatedPermissionsEditIdRouteImport } from './routes/_authenticated/permissions.edit.$id'
import { Route as AuthenticatedMitraEditIdRouteImport } from './routes/_authenticated/mitra.edit.$id'
import { Route as AuthenticatedJenisBarangEditIdRouteImport } from './routes/_authenticated/jenis-barang.edit.$id'
import { Route as AuthenticatedDepartemenEditIdRouteImport } from './routes/_authenticated/departemen.edit.$id'
import { Route as AuthenticatedBarangEditIdRouteImport } from './routes/_authenticated/barang.edit.$id'

const RegisterMitraRoute = RegisterMitraRouteImport.update({
  id: '/register-mitra',
  path: '/register-mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedWorkOrderRoute = AuthenticatedWorkOrderRouteImport.update({
  id: '/work-order',
  path: '/work-order',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportPengirimanRoute =
  AuthenticatedReportPengirimanRouteImport.update({
    id: '/report-pengiriman',
    path: '/report-pengiriman',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportPenerimaanRoute =
  AuthenticatedReportPenerimaanRouteImport.update({
    id: '/report-penerimaan',
    path: '/report-penerimaan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionSummaryRoute =
  AuthenticatedProductionSummaryRouteImport.update({
    id: '/production-summary',
    path: '/production-summary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPokemonRoute = AuthenticatedPokemonRouteImport.update({
  id: '/pokemon',
  path: '/pokemon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoInternalRoute = AuthenticatedPoInternalRouteImport.update({
  id: '/po-internal',
  path: '/po-internal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoClientRoute = AuthenticatedPoClientRouteImport.update({
  id: '/po-client',
  path: '/po-client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMitraRoute = AuthenticatedMitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJenisBarangRoute =
  AuthenticatedJenisBarangRouteImport.update({
    id: '/jenis-barang',
    path: '/jenis-barang',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartemenRoute = AuthenticatedDepartemenRouteImport.update({
  id: '/departemen',
  path: '/departemen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBarangRoute = AuthenticatedBarangRouteImport.update({
  id: '/barang',
  path: '/barang',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiEstimationRoute =
  AuthenticatedAiEstimationRouteImport.update({
    id: '/ai-estimation',
    path: '/ai-estimation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkOrderIndexRoute =
  AuthenticatedWorkOrderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkOrderRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRolesRoute,
} as any)
const AuthenticatedReportPengirimanIndexRoute =
  AuthenticatedReportPengirimanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportPengirimanRoute,
  } as any)
const AuthenticatedReportPenerimaanIndexRoute =
  AuthenticatedReportPenerimaanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportPenerimaanRoute,
  } as any)
const AuthenticatedPoInternalIndexRoute =
  AuthenticatedPoInternalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoInternalRoute,
  } as any)
const AuthenticatedPoClientIndexRoute =
  AuthenticatedPoClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoClientRoute,
  } as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPermissionsRoute,
  } as any)
const AuthenticatedMitraIndexRoute = AuthenticatedMitraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMitraRoute,
} as any)
const AuthenticatedJenisBarangIndexRoute =
  AuthenticatedJenisBarangIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedJenisBarangRoute,
  } as any)
const AuthenticatedDepartemenIndexRoute =
  AuthenticatedDepartemenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDepartemenRoute,
  } as any)
const AuthenticatedBarangIndexRoute =
  AuthenticatedBarangIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBarangRoute,
  } as any)
const AuthenticatedWorkOrderCreateRoute =
  AuthenticatedWorkOrderCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedWorkOrderRoute,
  } as any)
const AuthenticatedWorkOrderIdRoute =
  AuthenticatedWorkOrderIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWorkOrderRoute,
  } as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedRolesCreateRoute =
  AuthenticatedRolesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedRolesRoute,
  } as any)
const AuthenticatedReportPengirimanCreateRoute =
  AuthenticatedReportPengirimanCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedReportPengirimanRoute,
  } as any)
const AuthenticatedReportPengirimanIdRoute =
  AuthenticatedReportPengirimanIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedReportPengirimanRoute,
  } as any)
const AuthenticatedReportPenerimaanCreateRoute =
  AuthenticatedReportPenerimaanCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedReportPenerimaanRoute,
  } as any)
const AuthenticatedReportPenerimaanIdRoute =
  AuthenticatedReportPenerimaanIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedReportPenerimaanRoute,
  } as any)
const AuthenticatedPoInternalCreateRoute =
  AuthenticatedPoInternalCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedPoInternalRoute,
  } as any)
const AuthenticatedPoInternalIdRoute =
  AuthenticatedPoInternalIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPoInternalRoute,
  } as any)
const AuthenticatedPoClientCreateRoute =
  AuthenticatedPoClientCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedPoClientRoute,
  } as any)
const AuthenticatedPoClientIdRoute = AuthenticatedPoClientIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPoClientRoute,
} as any)
const AuthenticatedPermissionsCreateRoute =
  AuthenticatedPermissionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedPermissionsRoute,
  } as any)
const AuthenticatedPermissionsIdRoute =
  AuthenticatedPermissionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPermissionsRoute,
  } as any)
const AuthenticatedMitraCreateRoute =
  AuthenticatedMitraCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedMitraRoute,
  } as any)
const AuthenticatedMitraIdRoute = AuthenticatedMitraIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMitraRoute,
} as any)
const AuthenticatedJenisBarangCreateRoute =
  AuthenticatedJenisBarangCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedJenisBarangRoute,
  } as any)
const AuthenticatedJenisBarangIdRoute =
  AuthenticatedJenisBarangIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedJenisBarangRoute,
  } as any)
const AuthenticatedDepartemenCreateRoute =
  AuthenticatedDepartemenCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedDepartemenRoute,
  } as any)
const AuthenticatedDepartemenIdRoute =
  AuthenticatedDepartemenIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDepartemenRoute,
  } as any)
const AuthenticatedBarangCreateRoute =
  AuthenticatedBarangCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedBarangRoute,
  } as any)
const AuthenticatedBarangIdRoute = AuthenticatedBarangIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBarangRoute,
} as any)
const AuthenticatedWorkOrderEditIdRoute =
  AuthenticatedWorkOrderEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedWorkOrderRoute,
  } as any)
const AuthenticatedUsersEditIdRoute =
  AuthenticatedUsersEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedRolesEditIdRoute =
  AuthenticatedRolesEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedRolesRoute,
  } as any)
const AuthenticatedReportPengirimanEditIdRoute =
  AuthenticatedReportPengirimanEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedReportPengirimanRoute,
  } as any)
const AuthenticatedReportPenerimaanEditIdRoute =
  AuthenticatedReportPenerimaanEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedReportPenerimaanRoute,
  } as any)
const AuthenticatedPoClientEditIdRoute =
  AuthenticatedPoClientEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedPoClientRoute,
  } as any)
const AuthenticatedPermissionsEditIdRoute =
  AuthenticatedPermissionsEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedPermissionsRoute,
  } as any)
const AuthenticatedMitraEditIdRoute =
  AuthenticatedMitraEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedMitraRoute,
  } as any)
const AuthenticatedJenisBarangEditIdRoute =
  AuthenticatedJenisBarangEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedJenisBarangRoute,
  } as any)
const AuthenticatedDepartemenEditIdRoute =
  AuthenticatedDepartemenEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedDepartemenRoute,
  } as any)
const AuthenticatedBarangEditIdRoute =
  AuthenticatedBarangEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedBarangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register-mitra': typeof RegisterMitraRoute
  '/ai-estimation': typeof AuthenticatedAiEstimationRoute
  '/barang': typeof AuthenticatedBarangRouteWithChildren
  '/company': typeof AuthenticatedCompanyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departemen': typeof AuthenticatedDepartemenRouteWithChildren
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/jenis-barang': typeof AuthenticatedJenisBarangRouteWithChildren
  '/mitra': typeof AuthenticatedMitraRouteWithChildren
  '/permissions': typeof AuthenticatedPermissionsRouteWithChildren
  '/po-client': typeof AuthenticatedPoClientRouteWithChildren
  '/po-internal': typeof AuthenticatedPoInternalRouteWithChildren
  '/pokemon': typeof AuthenticatedPokemonRoute
  '/production-summary': typeof AuthenticatedProductionSummaryRoute
  '/report-penerimaan': typeof AuthenticatedReportPenerimaanRouteWithChildren
  '/report-pengiriman': typeof AuthenticatedReportPengirimanRouteWithChildren
  '/roles': typeof AuthenticatedRolesRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/work-order': typeof AuthenticatedWorkOrderRouteWithChildren
  '/barang/$id': typeof AuthenticatedBarangIdRoute
  '/barang/create': typeof AuthenticatedBarangCreateRoute
  '/departemen/$id': typeof AuthenticatedDepartemenIdRoute
  '/departemen/create': typeof AuthenticatedDepartemenCreateRoute
  '/jenis-barang/$id': typeof AuthenticatedJenisBarangIdRoute
  '/jenis-barang/create': typeof AuthenticatedJenisBarangCreateRoute
  '/mitra/$id': typeof AuthenticatedMitraIdRoute
  '/mitra/create': typeof AuthenticatedMitraCreateRoute
  '/permissions/$id': typeof AuthenticatedPermissionsIdRoute
  '/permissions/create': typeof AuthenticatedPermissionsCreateRoute
  '/po-client/$id': typeof AuthenticatedPoClientIdRoute
  '/po-client/create': typeof AuthenticatedPoClientCreateRoute
  '/po-internal/$id': typeof AuthenticatedPoInternalIdRoute
  '/po-internal/create': typeof AuthenticatedPoInternalCreateRoute
  '/report-penerimaan/$id': typeof AuthenticatedReportPenerimaanIdRoute
  '/report-penerimaan/create': typeof AuthenticatedReportPenerimaanCreateRoute
  '/report-pengiriman/$id': typeof AuthenticatedReportPengirimanIdRoute
  '/report-pengiriman/create': typeof AuthenticatedReportPengirimanCreateRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/work-order/$id': typeof AuthenticatedWorkOrderIdRoute
  '/work-order/create': typeof AuthenticatedWorkOrderCreateRoute
  '/barang/': typeof AuthenticatedBarangIndexRoute
  '/departemen/': typeof AuthenticatedDepartemenIndexRoute
  '/jenis-barang/': typeof AuthenticatedJenisBarangIndexRoute
  '/mitra/': typeof AuthenticatedMitraIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/po-client/': typeof AuthenticatedPoClientIndexRoute
  '/po-internal/': typeof AuthenticatedPoInternalIndexRoute
  '/report-penerimaan/': typeof AuthenticatedReportPenerimaanIndexRoute
  '/report-pengiriman/': typeof AuthenticatedReportPengirimanIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/work-order/': typeof AuthenticatedWorkOrderIndexRoute
  '/barang/edit/$id': typeof AuthenticatedBarangEditIdRoute
  '/departemen/edit/$id': typeof AuthenticatedDepartemenEditIdRoute
  '/jenis-barang/edit/$id': typeof AuthenticatedJenisBarangEditIdRoute
  '/mitra/edit/$id': typeof AuthenticatedMitraEditIdRoute
  '/permissions/edit/$id': typeof AuthenticatedPermissionsEditIdRoute
  '/po-client/edit/$id': typeof AuthenticatedPoClientEditIdRoute
  '/report-penerimaan/edit/$id': typeof AuthenticatedReportPenerimaanEditIdRoute
  '/report-pengiriman/edit/$id': typeof AuthenticatedReportPengirimanEditIdRoute
  '/roles/edit/$id': typeof AuthenticatedRolesEditIdRoute
  '/users/edit/$id': typeof AuthenticatedUsersEditIdRoute
  '/work-order/edit/$id': typeof AuthenticatedWorkOrderEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register-mitra': typeof RegisterMitraRoute
  '/ai-estimation': typeof AuthenticatedAiEstimationRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/pokemon': typeof AuthenticatedPokemonRoute
  '/production-summary': typeof AuthenticatedProductionSummaryRoute
  '/barang/$id': typeof AuthenticatedBarangIdRoute
  '/barang/create': typeof AuthenticatedBarangCreateRoute
  '/departemen/$id': typeof AuthenticatedDepartemenIdRoute
  '/departemen/create': typeof AuthenticatedDepartemenCreateRoute
  '/jenis-barang/$id': typeof AuthenticatedJenisBarangIdRoute
  '/jenis-barang/create': typeof AuthenticatedJenisBarangCreateRoute
  '/mitra/$id': typeof AuthenticatedMitraIdRoute
  '/mitra/create': typeof AuthenticatedMitraCreateRoute
  '/permissions/$id': typeof AuthenticatedPermissionsIdRoute
  '/permissions/create': typeof AuthenticatedPermissionsCreateRoute
  '/po-client/$id': typeof AuthenticatedPoClientIdRoute
  '/po-client/create': typeof AuthenticatedPoClientCreateRoute
  '/po-internal/$id': typeof AuthenticatedPoInternalIdRoute
  '/po-internal/create': typeof AuthenticatedPoInternalCreateRoute
  '/report-penerimaan/$id': typeof AuthenticatedReportPenerimaanIdRoute
  '/report-penerimaan/create': typeof AuthenticatedReportPenerimaanCreateRoute
  '/report-pengiriman/$id': typeof AuthenticatedReportPengirimanIdRoute
  '/report-pengiriman/create': typeof AuthenticatedReportPengirimanCreateRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/work-order/$id': typeof AuthenticatedWorkOrderIdRoute
  '/work-order/create': typeof AuthenticatedWorkOrderCreateRoute
  '/barang': typeof AuthenticatedBarangIndexRoute
  '/departemen': typeof AuthenticatedDepartemenIndexRoute
  '/jenis-barang': typeof AuthenticatedJenisBarangIndexRoute
  '/mitra': typeof AuthenticatedMitraIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/po-client': typeof AuthenticatedPoClientIndexRoute
  '/po-internal': typeof AuthenticatedPoInternalIndexRoute
  '/report-penerimaan': typeof AuthenticatedReportPenerimaanIndexRoute
  '/report-pengiriman': typeof AuthenticatedReportPengirimanIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/work-order': typeof AuthenticatedWorkOrderIndexRoute
  '/barang/edit/$id': typeof AuthenticatedBarangEditIdRoute
  '/departemen/edit/$id': typeof AuthenticatedDepartemenEditIdRoute
  '/jenis-barang/edit/$id': typeof AuthenticatedJenisBarangEditIdRoute
  '/mitra/edit/$id': typeof AuthenticatedMitraEditIdRoute
  '/permissions/edit/$id': typeof AuthenticatedPermissionsEditIdRoute
  '/po-client/edit/$id': typeof AuthenticatedPoClientEditIdRoute
  '/report-penerimaan/edit/$id': typeof AuthenticatedReportPenerimaanEditIdRoute
  '/report-pengiriman/edit/$id': typeof AuthenticatedReportPengirimanEditIdRoute
  '/roles/edit/$id': typeof AuthenticatedRolesEditIdRoute
  '/users/edit/$id': typeof AuthenticatedUsersEditIdRoute
  '/work-order/edit/$id': typeof AuthenticatedWorkOrderEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/register-mitra': typeof RegisterMitraRoute
  '/_authenticated/ai-estimation': typeof AuthenticatedAiEstimationRoute
  '/_authenticated/barang': typeof AuthenticatedBarangRouteWithChildren
  '/_authenticated/company': typeof AuthenticatedCompanyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departemen': typeof AuthenticatedDepartemenRouteWithChildren
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/jenis-barang': typeof AuthenticatedJenisBarangRouteWithChildren
  '/_authenticated/mitra': typeof AuthenticatedMitraRouteWithChildren
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRouteWithChildren
  '/_authenticated/po-client': typeof AuthenticatedPoClientRouteWithChildren
  '/_authenticated/po-internal': typeof AuthenticatedPoInternalRouteWithChildren
  '/_authenticated/pokemon': typeof AuthenticatedPokemonRoute
  '/_authenticated/production-summary': typeof AuthenticatedProductionSummaryRoute
  '/_authenticated/report-penerimaan': typeof AuthenticatedReportPenerimaanRouteWithChildren
  '/_authenticated/report-pengiriman': typeof AuthenticatedReportPengirimanRouteWithChildren
  '/_authenticated/roles': typeof AuthenticatedRolesRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/work-order': typeof AuthenticatedWorkOrderRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/barang/$id': typeof AuthenticatedBarangIdRoute
  '/_authenticated/barang/create': typeof AuthenticatedBarangCreateRoute
  '/_authenticated/departemen/$id': typeof AuthenticatedDepartemenIdRoute
  '/_authenticated/departemen/create': typeof AuthenticatedDepartemenCreateRoute
  '/_authenticated/jenis-barang/$id': typeof AuthenticatedJenisBarangIdRoute
  '/_authenticated/jenis-barang/create': typeof AuthenticatedJenisBarangCreateRoute
  '/_authenticated/mitra/$id': typeof AuthenticatedMitraIdRoute
  '/_authenticated/mitra/create': typeof AuthenticatedMitraCreateRoute
  '/_authenticated/permissions/$id': typeof AuthenticatedPermissionsIdRoute
  '/_authenticated/permissions/create': typeof AuthenticatedPermissionsCreateRoute
  '/_authenticated/po-client/$id': typeof AuthenticatedPoClientIdRoute
  '/_authenticated/po-client/create': typeof AuthenticatedPoClientCreateRoute
  '/_authenticated/po-internal/$id': typeof AuthenticatedPoInternalIdRoute
  '/_authenticated/po-internal/create': typeof AuthenticatedPoInternalCreateRoute
  '/_authenticated/report-penerimaan/$id': typeof AuthenticatedReportPenerimaanIdRoute
  '/_authenticated/report-penerimaan/create': typeof AuthenticatedReportPenerimaanCreateRoute
  '/_authenticated/report-pengiriman/$id': typeof AuthenticatedReportPengirimanIdRoute
  '/_authenticated/report-pengiriman/create': typeof AuthenticatedReportPengirimanCreateRoute
  '/_authenticated/roles/create': typeof AuthenticatedRolesCreateRoute
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/work-order/$id': typeof AuthenticatedWorkOrderIdRoute
  '/_authenticated/work-order/create': typeof AuthenticatedWorkOrderCreateRoute
  '/_authenticated/barang/': typeof AuthenticatedBarangIndexRoute
  '/_authenticated/departemen/': typeof AuthenticatedDepartemenIndexRoute
  '/_authenticated/jenis-barang/': typeof AuthenticatedJenisBarangIndexRoute
  '/_authenticated/mitra/': typeof AuthenticatedMitraIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/po-client/': typeof AuthenticatedPoClientIndexRoute
  '/_authenticated/po-internal/': typeof AuthenticatedPoInternalIndexRoute
  '/_authenticated/report-penerimaan/': typeof AuthenticatedReportPenerimaanIndexRoute
  '/_authenticated/report-pengiriman/': typeof AuthenticatedReportPengirimanIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/work-order/': typeof AuthenticatedWorkOrderIndexRoute
  '/_authenticated/barang/edit/$id': typeof AuthenticatedBarangEditIdRoute
  '/_authenticated/departemen/edit/$id': typeof AuthenticatedDepartemenEditIdRoute
  '/_authenticated/jenis-barang/edit/$id': typeof AuthenticatedJenisBarangEditIdRoute
  '/_authenticated/mitra/edit/$id': typeof AuthenticatedMitraEditIdRoute
  '/_authenticated/permissions/edit/$id': typeof AuthenticatedPermissionsEditIdRoute
  '/_authenticated/po-client/edit/$id': typeof AuthenticatedPoClientEditIdRoute
  '/_authenticated/report-penerimaan/edit/$id': typeof AuthenticatedReportPenerimaanEditIdRoute
  '/_authenticated/report-pengiriman/edit/$id': typeof AuthenticatedReportPengirimanEditIdRoute
  '/_authenticated/roles/edit/$id': typeof AuthenticatedRolesEditIdRoute
  '/_authenticated/users/edit/$id': typeof AuthenticatedUsersEditIdRoute
  '/_authenticated/work-order/edit/$id': typeof AuthenticatedWorkOrderEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register-mitra'
    | '/ai-estimation'
    | '/barang'
    | '/company'
    | '/dashboard'
    | '/departemen'
    | '/forbidden'
    | '/jenis-barang'
    | '/mitra'
    | '/permissions'
    | '/po-client'
    | '/po-internal'
    | '/pokemon'
    | '/production-summary'
    | '/report-penerimaan'
    | '/report-pengiriman'
    | '/roles'
    | '/users'
    | '/work-order'
    | '/barang/$id'
    | '/barang/create'
    | '/departemen/$id'
    | '/departemen/create'
    | '/jenis-barang/$id'
    | '/jenis-barang/create'
    | '/mitra/$id'
    | '/mitra/create'
    | '/permissions/$id'
    | '/permissions/create'
    | '/po-client/$id'
    | '/po-client/create'
    | '/po-internal/$id'
    | '/po-internal/create'
    | '/report-penerimaan/$id'
    | '/report-penerimaan/create'
    | '/report-pengiriman/$id'
    | '/report-pengiriman/create'
    | '/roles/create'
    | '/users/create'
    | '/work-order/$id'
    | '/work-order/create'
    | '/barang/'
    | '/departemen/'
    | '/jenis-barang/'
    | '/mitra/'
    | '/permissions/'
    | '/po-client/'
    | '/po-internal/'
    | '/report-penerimaan/'
    | '/report-pengiriman/'
    | '/roles/'
    | '/users/'
    | '/work-order/'
    | '/barang/edit/$id'
    | '/departemen/edit/$id'
    | '/jenis-barang/edit/$id'
    | '/mitra/edit/$id'
    | '/permissions/edit/$id'
    | '/po-client/edit/$id'
    | '/report-penerimaan/edit/$id'
    | '/report-pengiriman/edit/$id'
    | '/roles/edit/$id'
    | '/users/edit/$id'
    | '/work-order/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register-mitra'
    | '/ai-estimation'
    | '/company'
    | '/dashboard'
    | '/forbidden'
    | '/pokemon'
    | '/production-summary'
    | '/barang/$id'
    | '/barang/create'
    | '/departemen/$id'
    | '/departemen/create'
    | '/jenis-barang/$id'
    | '/jenis-barang/create'
    | '/mitra/$id'
    | '/mitra/create'
    | '/permissions/$id'
    | '/permissions/create'
    | '/po-client/$id'
    | '/po-client/create'
    | '/po-internal/$id'
    | '/po-internal/create'
    | '/report-penerimaan/$id'
    | '/report-penerimaan/create'
    | '/report-pengiriman/$id'
    | '/report-pengiriman/create'
    | '/roles/create'
    | '/users/create'
    | '/work-order/$id'
    | '/work-order/create'
    | '/barang'
    | '/departemen'
    | '/jenis-barang'
    | '/mitra'
    | '/permissions'
    | '/po-client'
    | '/po-internal'
    | '/report-penerimaan'
    | '/report-pengiriman'
    | '/roles'
    | '/users'
    | '/work-order'
    | '/barang/edit/$id'
    | '/departemen/edit/$id'
    | '/jenis-barang/edit/$id'
    | '/mitra/edit/$id'
    | '/permissions/edit/$id'
    | '/po-client/edit/$id'
    | '/report-penerimaan/edit/$id'
    | '/report-pengiriman/edit/$id'
    | '/roles/edit/$id'
    | '/users/edit/$id'
    | '/work-order/edit/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/login'
    | '/register-mitra'
    | '/_authenticated/ai-estimation'
    | '/_authenticated/barang'
    | '/_authenticated/company'
    | '/_authenticated/dashboard'
    | '/_authenticated/departemen'
    | '/_authenticated/forbidden'
    | '/_authenticated/jenis-barang'
    | '/_authenticated/mitra'
    | '/_authenticated/permissions'
    | '/_authenticated/po-client'
    | '/_authenticated/po-internal'
    | '/_authenticated/pokemon'
    | '/_authenticated/production-summary'
    | '/_authenticated/report-penerimaan'
    | '/_authenticated/report-pengiriman'
    | '/_authenticated/roles'
    | '/_authenticated/users'
    | '/_authenticated/work-order'
    | '/_public/'
    | '/_authenticated/barang/$id'
    | '/_authenticated/barang/create'
    | '/_authenticated/departemen/$id'
    | '/_authenticated/departemen/create'
    | '/_authenticated/jenis-barang/$id'
    | '/_authenticated/jenis-barang/create'
    | '/_authenticated/mitra/$id'
    | '/_authenticated/mitra/create'
    | '/_authenticated/permissions/$id'
    | '/_authenticated/permissions/create'
    | '/_authenticated/po-client/$id'
    | '/_authenticated/po-client/create'
    | '/_authenticated/po-internal/$id'
    | '/_authenticated/po-internal/create'
    | '/_authenticated/report-penerimaan/$id'
    | '/_authenticated/report-penerimaan/create'
    | '/_authenticated/report-pengiriman/$id'
    | '/_authenticated/report-pengiriman/create'
    | '/_authenticated/roles/create'
    | '/_authenticated/users/create'
    | '/_authenticated/work-order/$id'
    | '/_authenticated/work-order/create'
    | '/_authenticated/barang/'
    | '/_authenticated/departemen/'
    | '/_authenticated/jenis-barang/'
    | '/_authenticated/mitra/'
    | '/_authenticated/permissions/'
    | '/_authenticated/po-client/'
    | '/_authenticated/po-internal/'
    | '/_authenticated/report-penerimaan/'
    | '/_authenticated/report-pengiriman/'
    | '/_authenticated/roles/'
    | '/_authenticated/users/'
    | '/_authenticated/work-order/'
    | '/_authenticated/barang/edit/$id'
    | '/_authenticated/departemen/edit/$id'
    | '/_authenticated/jenis-barang/edit/$id'
    | '/_authenticated/mitra/edit/$id'
    | '/_authenticated/permissions/edit/$id'
    | '/_authenticated/po-client/edit/$id'
    | '/_authenticated/report-penerimaan/edit/$id'
    | '/_authenticated/report-pengiriman/edit/$id'
    | '/_authenticated/roles/edit/$id'
    | '/_authenticated/users/edit/$id'
    | '/_authenticated/work-order/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterMitraRoute: typeof RegisterMitraRoute
}

declare module '@tanstack/vue-router' {
  interface FileRoutesByPath {
    '/register-mitra': {
      id: '/register-mitra'
      path: '/register-mitra'
      fullPath: '/register-mitra'
      preLoaderRoute: typeof RegisterMitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/work-order': {
      id: '/_authenticated/work-order'
      path: '/work-order'
      fullPath: '/work-order'
      preLoaderRoute: typeof AuthenticatedWorkOrderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report-pengiriman': {
      id: '/_authenticated/report-pengiriman'
      path: '/report-pengiriman'
      fullPath: '/report-pengiriman'
      preLoaderRoute: typeof AuthenticatedReportPengirimanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report-penerimaan': {
      id: '/_authenticated/report-penerimaan'
      path: '/report-penerimaan'
      fullPath: '/report-penerimaan'
      preLoaderRoute: typeof AuthenticatedReportPenerimaanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production-summary': {
      id: '/_authenticated/production-summary'
      path: '/production-summary'
      fullPath: '/production-summary'
      preLoaderRoute: typeof AuthenticatedProductionSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pokemon': {
      id: '/_authenticated/pokemon'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof AuthenticatedPokemonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/po-internal': {
      id: '/_authenticated/po-internal'
      path: '/po-internal'
      fullPath: '/po-internal'
      preLoaderRoute: typeof AuthenticatedPoInternalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/po-client': {
      id: '/_authenticated/po-client'
      path: '/po-client'
      fullPath: '/po-client'
      preLoaderRoute: typeof AuthenticatedPoClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mitra': {
      id: '/_authenticated/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof AuthenticatedMitraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jenis-barang': {
      id: '/_authenticated/jenis-barang'
      path: '/jenis-barang'
      fullPath: '/jenis-barang'
      preLoaderRoute: typeof AuthenticatedJenisBarangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departemen': {
      id: '/_authenticated/departemen'
      path: '/departemen'
      fullPath: '/departemen'
      preLoaderRoute: typeof AuthenticatedDepartemenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barang': {
      id: '/_authenticated/barang'
      path: '/barang'
      fullPath: '/barang'
      preLoaderRoute: typeof AuthenticatedBarangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-estimation': {
      id: '/_authenticated/ai-estimation'
      path: '/ai-estimation'
      fullPath: '/ai-estimation'
      preLoaderRoute: typeof AuthenticatedAiEstimationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/work-order/': {
      id: '/_authenticated/work-order/'
      path: '/'
      fullPath: '/work-order/'
      preLoaderRoute: typeof AuthenticatedWorkOrderIndexRouteImport
      parentRoute: typeof AuthenticatedWorkOrderRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/report-pengiriman/': {
      id: '/_authenticated/report-pengiriman/'
      path: '/'
      fullPath: '/report-pengiriman/'
      preLoaderRoute: typeof AuthenticatedReportPengirimanIndexRouteImport
      parentRoute: typeof AuthenticatedReportPengirimanRoute
    }
    '/_authenticated/report-penerimaan/': {
      id: '/_authenticated/report-penerimaan/'
      path: '/'
      fullPath: '/report-penerimaan/'
      preLoaderRoute: typeof AuthenticatedReportPenerimaanIndexRouteImport
      parentRoute: typeof AuthenticatedReportPenerimaanRoute
    }
    '/_authenticated/po-internal/': {
      id: '/_authenticated/po-internal/'
      path: '/'
      fullPath: '/po-internal/'
      preLoaderRoute: typeof AuthenticatedPoInternalIndexRouteImport
      parentRoute: typeof AuthenticatedPoInternalRoute
    }
    '/_authenticated/po-client/': {
      id: '/_authenticated/po-client/'
      path: '/'
      fullPath: '/po-client/'
      preLoaderRoute: typeof AuthenticatedPoClientIndexRouteImport
      parentRoute: typeof AuthenticatedPoClientRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedPermissionsRoute
    }
    '/_authenticated/mitra/': {
      id: '/_authenticated/mitra/'
      path: '/'
      fullPath: '/mitra/'
      preLoaderRoute: typeof AuthenticatedMitraIndexRouteImport
      parentRoute: typeof AuthenticatedMitraRoute
    }
    '/_authenticated/jenis-barang/': {
      id: '/_authenticated/jenis-barang/'
      path: '/'
      fullPath: '/jenis-barang/'
      preLoaderRoute: typeof AuthenticatedJenisBarangIndexRouteImport
      parentRoute: typeof AuthenticatedJenisBarangRoute
    }
    '/_authenticated/departemen/': {
      id: '/_authenticated/departemen/'
      path: '/'
      fullPath: '/departemen/'
      preLoaderRoute: typeof AuthenticatedDepartemenIndexRouteImport
      parentRoute: typeof AuthenticatedDepartemenRoute
    }
    '/_authenticated/barang/': {
      id: '/_authenticated/barang/'
      path: '/'
      fullPath: '/barang/'
      preLoaderRoute: typeof AuthenticatedBarangIndexRouteImport
      parentRoute: typeof AuthenticatedBarangRoute
    }
    '/_authenticated/work-order/create': {
      id: '/_authenticated/work-order/create'
      path: '/create'
      fullPath: '/work-order/create'
      preLoaderRoute: typeof AuthenticatedWorkOrderCreateRouteImport
      parentRoute: typeof AuthenticatedWorkOrderRoute
    }
    '/_authenticated/work-order/$id': {
      id: '/_authenticated/work-order/$id'
      path: '/$id'
      fullPath: '/work-order/$id'
      preLoaderRoute: typeof AuthenticatedWorkOrderIdRouteImport
      parentRoute: typeof AuthenticatedWorkOrderRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/roles/create': {
      id: '/_authenticated/roles/create'
      path: '/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AuthenticatedRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/report-pengiriman/create': {
      id: '/_authenticated/report-pengiriman/create'
      path: '/create'
      fullPath: '/report-pengiriman/create'
      preLoaderRoute: typeof AuthenticatedReportPengirimanCreateRouteImport
      parentRoute: typeof AuthenticatedReportPengirimanRoute
    }
    '/_authenticated/report-pengiriman/$id': {
      id: '/_authenticated/report-pengiriman/$id'
      path: '/$id'
      fullPath: '/report-pengiriman/$id'
      preLoaderRoute: typeof AuthenticatedReportPengirimanIdRouteImport
      parentRoute: typeof AuthenticatedReportPengirimanRoute
    }
    '/_authenticated/report-penerimaan/create': {
      id: '/_authenticated/report-penerimaan/create'
      path: '/create'
      fullPath: '/report-penerimaan/create'
      preLoaderRoute: typeof AuthenticatedReportPenerimaanCreateRouteImport
      parentRoute: typeof AuthenticatedReportPenerimaanRoute
    }
    '/_authenticated/report-penerimaan/$id': {
      id: '/_authenticated/report-penerimaan/$id'
      path: '/$id'
      fullPath: '/report-penerimaan/$id'
      preLoaderRoute: typeof AuthenticatedReportPenerimaanIdRouteImport
      parentRoute: typeof AuthenticatedReportPenerimaanRoute
    }
    '/_authenticated/po-internal/create': {
      id: '/_authenticated/po-internal/create'
      path: '/create'
      fullPath: '/po-internal/create'
      preLoaderRoute: typeof AuthenticatedPoInternalCreateRouteImport
      parentRoute: typeof AuthenticatedPoInternalRoute
    }
    '/_authenticated/po-internal/$id': {
      id: '/_authenticated/po-internal/$id'
      path: '/$id'
      fullPath: '/po-internal/$id'
      preLoaderRoute: typeof AuthenticatedPoInternalIdRouteImport
      parentRoute: typeof AuthenticatedPoInternalRoute
    }
    '/_authenticated/po-client/create': {
      id: '/_authenticated/po-client/create'
      path: '/create'
      fullPath: '/po-client/create'
      preLoaderRoute: typeof AuthenticatedPoClientCreateRouteImport
      parentRoute: typeof AuthenticatedPoClientRoute
    }
    '/_authenticated/po-client/$id': {
      id: '/_authenticated/po-client/$id'
      path: '/$id'
      fullPath: '/po-client/$id'
      preLoaderRoute: typeof AuthenticatedPoClientIdRouteImport
      parentRoute: typeof AuthenticatedPoClientRoute
    }
    '/_authenticated/permissions/create': {
      id: '/_authenticated/permissions/create'
      path: '/create'
      fullPath: '/permissions/create'
      preLoaderRoute: typeof AuthenticatedPermissionsCreateRouteImport
      parentRoute: typeof AuthenticatedPermissionsRoute
    }
    '/_authenticated/permissions/$id': {
      id: '/_authenticated/permissions/$id'
      path: '/$id'
      fullPath: '/permissions/$id'
      preLoaderRoute: typeof AuthenticatedPermissionsIdRouteImport
      parentRoute: typeof AuthenticatedPermissionsRoute
    }
    '/_authenticated/mitra/create': {
      id: '/_authenticated/mitra/create'
      path: '/create'
      fullPath: '/mitra/create'
      preLoaderRoute: typeof AuthenticatedMitraCreateRouteImport
      parentRoute: typeof AuthenticatedMitraRoute
    }
    '/_authenticated/mitra/$id': {
      id: '/_authenticated/mitra/$id'
      path: '/$id'
      fullPath: '/mitra/$id'
      preLoaderRoute: typeof AuthenticatedMitraIdRouteImport
      parentRoute: typeof AuthenticatedMitraRoute
    }
    '/_authenticated/jenis-barang/create': {
      id: '/_authenticated/jenis-barang/create'
      path: '/create'
      fullPath: '/jenis-barang/create'
      preLoaderRoute: typeof AuthenticatedJenisBarangCreateRouteImport
      parentRoute: typeof AuthenticatedJenisBarangRoute
    }
    '/_authenticated/jenis-barang/$id': {
      id: '/_authenticated/jenis-barang/$id'
      path: '/$id'
      fullPath: '/jenis-barang/$id'
      preLoaderRoute: typeof AuthenticatedJenisBarangIdRouteImport
      parentRoute: typeof AuthenticatedJenisBarangRoute
    }
    '/_authenticated/departemen/create': {
      id: '/_authenticated/departemen/create'
      path: '/create'
      fullPath: '/departemen/create'
      preLoaderRoute: typeof AuthenticatedDepartemenCreateRouteImport
      parentRoute: typeof AuthenticatedDepartemenRoute
    }
    '/_authenticated/departemen/$id': {
      id: '/_authenticated/departemen/$id'
      path: '/$id'
      fullPath: '/departemen/$id'
      preLoaderRoute: typeof AuthenticatedDepartemenIdRouteImport
      parentRoute: typeof AuthenticatedDepartemenRoute
    }
    '/_authenticated/barang/create': {
      id: '/_authenticated/barang/create'
      path: '/create'
      fullPath: '/barang/create'
      preLoaderRoute: typeof AuthenticatedBarangCreateRouteImport
      parentRoute: typeof AuthenticatedBarangRoute
    }
    '/_authenticated/barang/$id': {
      id: '/_authenticated/barang/$id'
      path: '/$id'
      fullPath: '/barang/$id'
      preLoaderRoute: typeof AuthenticatedBarangIdRouteImport
      parentRoute: typeof AuthenticatedBarangRoute
    }
    '/_authenticated/work-order/edit/$id': {
      id: '/_authenticated/work-order/edit/$id'
      path: '/edit/$id'
      fullPath: '/work-order/edit/$id'
      preLoaderRoute: typeof AuthenticatedWorkOrderEditIdRouteImport
      parentRoute: typeof AuthenticatedWorkOrderRoute
    }
    '/_authenticated/users/edit/$id': {
      id: '/_authenticated/users/edit/$id'
      path: '/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof AuthenticatedUsersEditIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/roles/edit/$id': {
      id: '/_authenticated/roles/edit/$id'
      path: '/edit/$id'
      fullPath: '/roles/edit/$id'
      preLoaderRoute: typeof AuthenticatedRolesEditIdRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/report-pengiriman/edit/$id': {
      id: '/_authenticated/report-pengiriman/edit/$id'
      path: '/edit/$id'
      fullPath: '/report-pengiriman/edit/$id'
      preLoaderRoute: typeof AuthenticatedReportPengirimanEditIdRouteImport
      parentRoute: typeof AuthenticatedReportPengirimanRoute
    }
    '/_authenticated/report-penerimaan/edit/$id': {
      id: '/_authenticated/report-penerimaan/edit/$id'
      path: '/edit/$id'
      fullPath: '/report-penerimaan/edit/$id'
      preLoaderRoute: typeof AuthenticatedReportPenerimaanEditIdRouteImport
      parentRoute: typeof AuthenticatedReportPenerimaanRoute
    }
    '/_authenticated/po-client/edit/$id': {
      id: '/_authenticated/po-client/edit/$id'
      path: '/edit/$id'
      fullPath: '/po-client/edit/$id'
      preLoaderRoute: typeof AuthenticatedPoClientEditIdRouteImport
      parentRoute: typeof AuthenticatedPoClientRoute
    }
    '/_authenticated/permissions/edit/$id': {
      id: '/_authenticated/permissions/edit/$id'
      path: '/edit/$id'
      fullPath: '/permissions/edit/$id'
      preLoaderRoute: typeof AuthenticatedPermissionsEditIdRouteImport
      parentRoute: typeof AuthenticatedPermissionsRoute
    }
    '/_authenticated/mitra/edit/$id': {
      id: '/_authenticated/mitra/edit/$id'
      path: '/edit/$id'
      fullPath: '/mitra/edit/$id'
      preLoaderRoute: typeof AuthenticatedMitraEditIdRouteImport
      parentRoute: typeof AuthenticatedMitraRoute
    }
    '/_authenticated/jenis-barang/edit/$id': {
      id: '/_authenticated/jenis-barang/edit/$id'
      path: '/edit/$id'
      fullPath: '/jenis-barang/edit/$id'
      preLoaderRoute: typeof AuthenticatedJenisBarangEditIdRouteImport
      parentRoute: typeof AuthenticatedJenisBarangRoute
    }
    '/_authenticated/departemen/edit/$id': {
      id: '/_authenticated/departemen/edit/$id'
      path: '/edit/$id'
      fullPath: '/departemen/edit/$id'
      preLoaderRoute: typeof AuthenticatedDepartemenEditIdRouteImport
      parentRoute: typeof AuthenticatedDepartemenRoute
    }
    '/_authenticated/barang/edit/$id': {
      id: '/_authenticated/barang/edit/$id'
      path: '/edit/$id'
      fullPath: '/barang/edit/$id'
      preLoaderRoute: typeof AuthenticatedBarangEditIdRouteImport
      parentRoute: typeof AuthenticatedBarangRoute
    }
  }
}

interface AuthenticatedBarangRouteChildren {
  AuthenticatedBarangIdRoute: typeof AuthenticatedBarangIdRoute
  AuthenticatedBarangCreateRoute: typeof AuthenticatedBarangCreateRoute
  AuthenticatedBarangIndexRoute: typeof AuthenticatedBarangIndexRoute
  AuthenticatedBarangEditIdRoute: typeof AuthenticatedBarangEditIdRoute
}

const AuthenticatedBarangRouteChildren: AuthenticatedBarangRouteChildren = {
  AuthenticatedBarangIdRoute: AuthenticatedBarangIdRoute,
  AuthenticatedBarangCreateRoute: AuthenticatedBarangCreateRoute,
  AuthenticatedBarangIndexRoute: AuthenticatedBarangIndexRoute,
  AuthenticatedBarangEditIdRoute: AuthenticatedBarangEditIdRoute,
}

const AuthenticatedBarangRouteWithChildren =
  AuthenticatedBarangRoute._addFileChildren(AuthenticatedBarangRouteChildren)

interface AuthenticatedDepartemenRouteChildren {
  AuthenticatedDepartemenIdRoute: typeof AuthenticatedDepartemenIdRoute
  AuthenticatedDepartemenCreateRoute: typeof AuthenticatedDepartemenCreateRoute
  AuthenticatedDepartemenIndexRoute: typeof AuthenticatedDepartemenIndexRoute
  AuthenticatedDepartemenEditIdRoute: typeof AuthenticatedDepartemenEditIdRoute
}

const AuthenticatedDepartemenRouteChildren: AuthenticatedDepartemenRouteChildren =
  {
    AuthenticatedDepartemenIdRoute: AuthenticatedDepartemenIdRoute,
    AuthenticatedDepartemenCreateRoute: AuthenticatedDepartemenCreateRoute,
    AuthenticatedDepartemenIndexRoute: AuthenticatedDepartemenIndexRoute,
    AuthenticatedDepartemenEditIdRoute: AuthenticatedDepartemenEditIdRoute,
  }

const AuthenticatedDepartemenRouteWithChildren =
  AuthenticatedDepartemenRoute._addFileChildren(
    AuthenticatedDepartemenRouteChildren,
  )

interface AuthenticatedJenisBarangRouteChildren {
  AuthenticatedJenisBarangIdRoute: typeof AuthenticatedJenisBarangIdRoute
  AuthenticatedJenisBarangCreateRoute: typeof AuthenticatedJenisBarangCreateRoute
  AuthenticatedJenisBarangIndexRoute: typeof AuthenticatedJenisBarangIndexRoute
  AuthenticatedJenisBarangEditIdRoute: typeof AuthenticatedJenisBarangEditIdRoute
}

const AuthenticatedJenisBarangRouteChildren: AuthenticatedJenisBarangRouteChildren =
  {
    AuthenticatedJenisBarangIdRoute: AuthenticatedJenisBarangIdRoute,
    AuthenticatedJenisBarangCreateRoute: AuthenticatedJenisBarangCreateRoute,
    AuthenticatedJenisBarangIndexRoute: AuthenticatedJenisBarangIndexRoute,
    AuthenticatedJenisBarangEditIdRoute: AuthenticatedJenisBarangEditIdRoute,
  }

const AuthenticatedJenisBarangRouteWithChildren =
  AuthenticatedJenisBarangRoute._addFileChildren(
    AuthenticatedJenisBarangRouteChildren,
  )

interface AuthenticatedMitraRouteChildren {
  AuthenticatedMitraIdRoute: typeof AuthenticatedMitraIdRoute
  AuthenticatedMitraCreateRoute: typeof AuthenticatedMitraCreateRoute
  AuthenticatedMitraIndexRoute: typeof AuthenticatedMitraIndexRoute
  AuthenticatedMitraEditIdRoute: typeof AuthenticatedMitraEditIdRoute
}

const AuthenticatedMitraRouteChildren: AuthenticatedMitraRouteChildren = {
  AuthenticatedMitraIdRoute: AuthenticatedMitraIdRoute,
  AuthenticatedMitraCreateRoute: AuthenticatedMitraCreateRoute,
  AuthenticatedMitraIndexRoute: AuthenticatedMitraIndexRoute,
  AuthenticatedMitraEditIdRoute: AuthenticatedMitraEditIdRoute,
}

const AuthenticatedMitraRouteWithChildren =
  AuthenticatedMitraRoute._addFileChildren(AuthenticatedMitraRouteChildren)

interface AuthenticatedPermissionsRouteChildren {
  AuthenticatedPermissionsIdRoute: typeof AuthenticatedPermissionsIdRoute
  AuthenticatedPermissionsCreateRoute: typeof AuthenticatedPermissionsCreateRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedPermissionsEditIdRoute: typeof AuthenticatedPermissionsEditIdRoute
}

const AuthenticatedPermissionsRouteChildren: AuthenticatedPermissionsRouteChildren =
  {
    AuthenticatedPermissionsIdRoute: AuthenticatedPermissionsIdRoute,
    AuthenticatedPermissionsCreateRoute: AuthenticatedPermissionsCreateRoute,
    AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
    AuthenticatedPermissionsEditIdRoute: AuthenticatedPermissionsEditIdRoute,
  }

const AuthenticatedPermissionsRouteWithChildren =
  AuthenticatedPermissionsRoute._addFileChildren(
    AuthenticatedPermissionsRouteChildren,
  )

interface AuthenticatedPoClientRouteChildren {
  AuthenticatedPoClientIdRoute: typeof AuthenticatedPoClientIdRoute
  AuthenticatedPoClientCreateRoute: typeof AuthenticatedPoClientCreateRoute
  AuthenticatedPoClientIndexRoute: typeof AuthenticatedPoClientIndexRoute
  AuthenticatedPoClientEditIdRoute: typeof AuthenticatedPoClientEditIdRoute
}

const AuthenticatedPoClientRouteChildren: AuthenticatedPoClientRouteChildren = {
  AuthenticatedPoClientIdRoute: AuthenticatedPoClientIdRoute,
  AuthenticatedPoClientCreateRoute: AuthenticatedPoClientCreateRoute,
  AuthenticatedPoClientIndexRoute: AuthenticatedPoClientIndexRoute,
  AuthenticatedPoClientEditIdRoute: AuthenticatedPoClientEditIdRoute,
}

const AuthenticatedPoClientRouteWithChildren =
  AuthenticatedPoClientRoute._addFileChildren(
    AuthenticatedPoClientRouteChildren,
  )

interface AuthenticatedPoInternalRouteChildren {
  AuthenticatedPoInternalIdRoute: typeof AuthenticatedPoInternalIdRoute
  AuthenticatedPoInternalCreateRoute: typeof AuthenticatedPoInternalCreateRoute
  AuthenticatedPoInternalIndexRoute: typeof AuthenticatedPoInternalIndexRoute
}

const AuthenticatedPoInternalRouteChildren: AuthenticatedPoInternalRouteChildren =
  {
    AuthenticatedPoInternalIdRoute: AuthenticatedPoInternalIdRoute,
    AuthenticatedPoInternalCreateRoute: AuthenticatedPoInternalCreateRoute,
    AuthenticatedPoInternalIndexRoute: AuthenticatedPoInternalIndexRoute,
  }

const AuthenticatedPoInternalRouteWithChildren =
  AuthenticatedPoInternalRoute._addFileChildren(
    AuthenticatedPoInternalRouteChildren,
  )

interface AuthenticatedReportPenerimaanRouteChildren {
  AuthenticatedReportPenerimaanIdRoute: typeof AuthenticatedReportPenerimaanIdRoute
  AuthenticatedReportPenerimaanCreateRoute: typeof AuthenticatedReportPenerimaanCreateRoute
  AuthenticatedReportPenerimaanIndexRoute: typeof AuthenticatedReportPenerimaanIndexRoute
  AuthenticatedReportPenerimaanEditIdRoute: typeof AuthenticatedReportPenerimaanEditIdRoute
}

const AuthenticatedReportPenerimaanRouteChildren: AuthenticatedReportPenerimaanRouteChildren =
  {
    AuthenticatedReportPenerimaanIdRoute: AuthenticatedReportPenerimaanIdRoute,
    AuthenticatedReportPenerimaanCreateRoute:
      AuthenticatedReportPenerimaanCreateRoute,
    AuthenticatedReportPenerimaanIndexRoute:
      AuthenticatedReportPenerimaanIndexRoute,
    AuthenticatedReportPenerimaanEditIdRoute:
      AuthenticatedReportPenerimaanEditIdRoute,
  }

const AuthenticatedReportPenerimaanRouteWithChildren =
  AuthenticatedReportPenerimaanRoute._addFileChildren(
    AuthenticatedReportPenerimaanRouteChildren,
  )

interface AuthenticatedReportPengirimanRouteChildren {
  AuthenticatedReportPengirimanIdRoute: typeof AuthenticatedReportPengirimanIdRoute
  AuthenticatedReportPengirimanCreateRoute: typeof AuthenticatedReportPengirimanCreateRoute
  AuthenticatedReportPengirimanIndexRoute: typeof AuthenticatedReportPengirimanIndexRoute
  AuthenticatedReportPengirimanEditIdRoute: typeof AuthenticatedReportPengirimanEditIdRoute
}

const AuthenticatedReportPengirimanRouteChildren: AuthenticatedReportPengirimanRouteChildren =
  {
    AuthenticatedReportPengirimanIdRoute: AuthenticatedReportPengirimanIdRoute,
    AuthenticatedReportPengirimanCreateRoute:
      AuthenticatedReportPengirimanCreateRoute,
    AuthenticatedReportPengirimanIndexRoute:
      AuthenticatedReportPengirimanIndexRoute,
    AuthenticatedReportPengirimanEditIdRoute:
      AuthenticatedReportPengirimanEditIdRoute,
  }

const AuthenticatedReportPengirimanRouteWithChildren =
  AuthenticatedReportPengirimanRoute._addFileChildren(
    AuthenticatedReportPengirimanRouteChildren,
  )

interface AuthenticatedRolesRouteChildren {
  AuthenticatedRolesCreateRoute: typeof AuthenticatedRolesCreateRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedRolesEditIdRoute: typeof AuthenticatedRolesEditIdRoute
}

const AuthenticatedRolesRouteChildren: AuthenticatedRolesRouteChildren = {
  AuthenticatedRolesCreateRoute: AuthenticatedRolesCreateRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedRolesEditIdRoute: AuthenticatedRolesEditIdRoute,
}

const AuthenticatedRolesRouteWithChildren =
  AuthenticatedRolesRoute._addFileChildren(AuthenticatedRolesRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUsersEditIdRoute: typeof AuthenticatedUsersEditIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUsersEditIdRoute: AuthenticatedUsersEditIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedWorkOrderRouteChildren {
  AuthenticatedWorkOrderIdRoute: typeof AuthenticatedWorkOrderIdRoute
  AuthenticatedWorkOrderCreateRoute: typeof AuthenticatedWorkOrderCreateRoute
  AuthenticatedWorkOrderIndexRoute: typeof AuthenticatedWorkOrderIndexRoute
  AuthenticatedWorkOrderEditIdRoute: typeof AuthenticatedWorkOrderEditIdRoute
}

const AuthenticatedWorkOrderRouteChildren: AuthenticatedWorkOrderRouteChildren =
  {
    AuthenticatedWorkOrderIdRoute: AuthenticatedWorkOrderIdRoute,
    AuthenticatedWorkOrderCreateRoute: AuthenticatedWorkOrderCreateRoute,
    AuthenticatedWorkOrderIndexRoute: AuthenticatedWorkOrderIndexRoute,
    AuthenticatedWorkOrderEditIdRoute: AuthenticatedWorkOrderEditIdRoute,
  }

const AuthenticatedWorkOrderRouteWithChildren =
  AuthenticatedWorkOrderRoute._addFileChildren(
    AuthenticatedWorkOrderRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiEstimationRoute: typeof AuthenticatedAiEstimationRoute
  AuthenticatedBarangRoute: typeof AuthenticatedBarangRouteWithChildren
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartemenRoute: typeof AuthenticatedDepartemenRouteWithChildren
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedJenisBarangRoute: typeof AuthenticatedJenisBarangRouteWithChildren
  AuthenticatedMitraRoute: typeof AuthenticatedMitraRouteWithChildren
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRouteWithChildren
  AuthenticatedPoClientRoute: typeof AuthenticatedPoClientRouteWithChildren
  AuthenticatedPoInternalRoute: typeof AuthenticatedPoInternalRouteWithChildren
  AuthenticatedPokemonRoute: typeof AuthenticatedPokemonRoute
  AuthenticatedProductionSummaryRoute: typeof AuthenticatedProductionSummaryRoute
  AuthenticatedReportPenerimaanRoute: typeof AuthenticatedReportPenerimaanRouteWithChildren
  AuthenticatedReportPengirimanRoute: typeof AuthenticatedReportPengirimanRouteWithChildren
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedWorkOrderRoute: typeof AuthenticatedWorkOrderRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiEstimationRoute: AuthenticatedAiEstimationRoute,
  AuthenticatedBarangRoute: AuthenticatedBarangRouteWithChildren,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartemenRoute: AuthenticatedDepartemenRouteWithChildren,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedJenisBarangRoute: AuthenticatedJenisBarangRouteWithChildren,
  AuthenticatedMitraRoute: AuthenticatedMitraRouteWithChildren,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRouteWithChildren,
  AuthenticatedPoClientRoute: AuthenticatedPoClientRouteWithChildren,
  AuthenticatedPoInternalRoute: AuthenticatedPoInternalRouteWithChildren,
  AuthenticatedPokemonRoute: AuthenticatedPokemonRoute,
  AuthenticatedProductionSummaryRoute: AuthenticatedProductionSummaryRoute,
  AuthenticatedReportPenerimaanRoute:
    AuthenticatedReportPenerimaanRouteWithChildren,
  AuthenticatedReportPengirimanRoute:
    AuthenticatedReportPengirimanRouteWithChildren,
  AuthenticatedRolesRoute: AuthenticatedRolesRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedWorkOrderRoute: AuthenticatedWorkOrderRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterMitraRoute: RegisterMitraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
